where-clause = WHERE conds
conds = cond (LO cond)*
cond = atom-cond | OP conds CP | sensitive-conds
atom-cond = compare-expr 
<compare-expr> = le CO re
sensitive-conds = OB conds CB
<le> = FIELD | func
<re> = FIELD | STR | KID | func | value-list
value-list = OP KID CP
func = FIELD OP cols? CP 
cols = col (<COMMA> col)*
col = FIELD | STR | KID | func 
COMMA = ','
<OP> = '('
<CP> = ')'
<OB> = '['
<CB> = ']'
<NOT> = 'not'
<WHERE> = 'where'
<FIELD> = #"([-\w]+\.)*[-\w]+"
KID = #"(:[-\w]+\*?)?:[^-\s(:)\[\],.+*/]+"
<LO> = 'and' | 'or'
<CO> = '=' | '>=' | '<=' | '!=' | '<>' | 'like' | 'is' | 'is' NOT? | NOT? 'in' | '>' | '<'
<STR> = #"'.+?'"
