where-clause = WHERE conds
conds = cond+
cond = elements | LB (elements/cond)+ RB
<elements> = element+
<element> = ((KID | STR) / ANY)
KID = #"(:[-\w]+\*?)?:[-\w]+"
<LB> = '['
<RB> = ']'
<STR> = #"'.+?'" | #'".+?"'
<ANY> = #'[^\[\]\s]+'
<WHERE> = 'where' | 'WHERE'
