(* 用于分析查询列表函数的语法 *)
prog = fn+
(* 函数体定义 *)
fn = <COMMENT*> header <COMMENT*> sqls
header = <'-- :name '> FN-NAME <SPACE_LF>
COMMENT = #'--(?! :name ).+' <SPACE_LF>
sqls = (<COMMENT> | SQL)+
<SQL> = #"^(?!--).+" <SPACE_LF>?
<FN-NAME> = #"[\w-]+"
SPACE_LF = #"\s*\n\s*"
